"""empty message

Revision ID: 36a884725e92
Revises: 55a604399332
Create Date: 2020-11-08 00:02:10.754195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a884725e92'
down_revision = '55a604399332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_state', sa.Column('definition', sa.String(), nullable=True))
    op.drop_column('users_state', 'def')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_state', sa.Column('def', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users_state', 'definition')
    # ### end Alembic commands ###
