"""empty message

Revision ID: ad129a42a603
Revises: 36a884725e92
Create Date: 2020-11-08 00:19:40.218373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad129a42a603'
down_revision = '36a884725e92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defs', sa.Column('guessed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('defs', 'guessed')
    # ### end Alembic commands ###
